### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by asmaratantra** [philmerrell/ionic-audiobar#2]
Runtime Error
Error in ./MyApp class MyApp - caused by: __WEBPACK_IMPORTED_MODULE_2_ionic_audiobar__.Track is not a constructor
Stack
TypeError: __WEBPACK_IMPORTED_MODULE_2_ionic_audiobar__.Track is not a constructor
    at new HomePage (http://localhost:8100/build/main.js:59170:13)
    at new Wrapper_HomePage (/AppModule/HomePage/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomePage_Host0.createInternal (/AppModule/HomePage/host.ngfactory.js:15:24)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:8100/build/main.js:101500:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:8100/build/main.js:101760:52)
    at ComponentFactory.create (http://localhost:8100/build/main.js:37154:25)
    at NavControllerBase._viewInit (http://localhost:8100/build/main.js:29659:44)
    at NavControllerBase._nextTrns (http://localhost:8100/build/main.js:29488:18)
    at NavControllerBase._queueTrns (http://localhost:8100/build/main.js:29459:14)
    at NavControllerBase.push (http://localhost:8100/build/main.js:29303:21)

**Comment by philmerrell** [comment]
Thanks, for checking it out.  Honestly, I didn't expect anyone to notice this component yet.

Still very much in development mode so I'm not surprised it's not working.  

Probably going to need a little more info to fix what you're seeing.  If you can post your component code, I'll take a look.  You can also check out the demo folder to see an example, but there's still a lot that needs to be addressed for sure.

If you still need a component like this in the future, check back in a little while, it's still very much an alpha component, and I should probably tag it as much.

Thanks.

**Comment by philmerrell** [comment]
I updated the usage instructions in the readme to demonstrate importing the audiobar module in addition to adding it to the imports array of your main app module file.  If you're still having trouble feel free to post example code and I'll take a look.
